[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.13"
# evm_version = "prague" # Shouldn't be necessary

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Zircuit RPC configuration
[rpc_endpoints]
zircuit_mainnet = "https://mainnet.zircuit.com"
garfield_testnet = "https://garfield-testnet.zircuit.com"

amoy_testnet = "https://rpc-amoy.polygon.technology/"
