[package]
name = "noir"
type = "bin"
authors = [""]

[dependencies]
# bignum = { tag = "v0.8.2", git = "https://github.com/noir-lang/noir-bignum" }
# bignum = { tag = "main", git = "https://github.com/noir-lang/noir-bignum" }
