address = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
amount = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
max_amount = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
whitelist = [["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]]
