address = { inner = [64, 74, 26, 253, 61, 23, 236, 46, 123, 193, 181, 181, 46, 158, 12, 127, 206, 229, 50, 178] }
# amount = 1000000000000000000 # 1   ETH
  amount =  500000000000000000 # 0.5 ETH

whitelist = [{ inner = [64, 74, 26, 253, 61, 23, 236, 46, 123, 193, 181, 181, 46, 158, 12, 127, 206, 229, 50, 178] }]
max_amount = 1000000000000000000
